apiVersion: v1
kind: PersistentVolume
metadata:
        name: redis-data-redis-app-master-0
        labels:
                app: redis
                component: master
                heritage: Helm
                role: master
                release: redis-app
spec:
        capacity:
                storage: 1Gi #8Gi 
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: /mnt/redis-app-master-0
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#        name: redis-data-redis-app-master-1
#        labels:
#                app: redis
#                component: master
#                heritage: helm
#                role: master
#                release: redis-app
#spec:
#        capacity:
#                storage: 8Gi
#        accessModes:
#                - ReadWriteOnce
#        hostPath:
#                path: /mnt/redis-app-master-1
