apiVersion: v1
kind: ConfigMap
metadata:
   namespace: app
   name: flask
data:
   app.py: |- 
       import time

       import redis
       from flask import Flask

       import os

       app = Flask(__name__)
       #cache = redis.Redis(host='redis', port=6379)
       cache = redis.Redis(host=os.environ['REDIS_MASTER_SERVICE_HOST'], port=6379)

       def get_hit_count():
           retries = 5
           while True:
               try:
                   return cache.incr('hits')
               except redis.exceptions.ConnectionError as exc:
                    if retries == 0:
                        raise exc
                    retries -= 1
                    time.sleep(0.5)


       @app.route('/')
       def hello():
           count = get_hit_count()
           return 'Hello World! I have been seen {} times.\n'.format(count)
