apiVersion: v1
kind: Service
metadata:
    name: frontend-svc
    labels:
        app: frontend
    namespace: app
spec:
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    type: LoadBalancer
    selector:
        app: frontend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: frontend
   namespace: app
spec:
   replicas: 2
   selector:
       matchLabels:
           app: frontend
   serviceName: "frontend-svc"
   template:
       metadata:
           name: frontend
           labels:
               app: frontend
           namespace: app
       spec:
           containers:
                - image: jongablop/flask-frontend:arm64
                  name: flask-frontend
                  volumeMounts:
                  - mountPath: /code
                    name: vol
                  ports:
                  - containerPort: 5000
                  env:
                  - name: REDIS_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: redis-app
                            key: redis-password
                  - name: MY_POD_NAME
                    valueFrom:
                        fieldRef:
                            fieldPath: metadata.name
           nodeSelector:                
               arch: arm
           volumes:
              - name: vol
                configMap:
                    name: flask
                    items:
                       - key: app.py
                         path: app.py
