apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: redis-data-redis-app-master-0
        namespace: app
        labels:
                app: redis
                component: master
                heritage: Helm
                role: master
                release: redis-app
spec:
        #storageClassName: manual
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: redis-data-redis-app-slave-0
        namespace: app
        labels:
                app: redis
                component: slave
                heritage: Helm
                role: slave
                release: redis-app
spec:
        #storageClassName: manual
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 8Gi

