apiVersion: v1
kind: PersistentVolume
metadata:
        name: redis-data-redis-app-master-0
        labels:
                app: redis
                component: master
                heritage: Helm
                role: master
                release: redis-app
spec:
        #storageClassName: manual
        capacity:
                storage: 8Gi 
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: /mnt/redis-app-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
        name: redis-data-redis-app-slave-0
spec:
        #storageClassName: manual
        capacity:
                storage: 8Gi
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: /mnt/redis-app-slave-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
        name: redis-data-redis-app-slave-1
spec:
        #storageClassName: manual
        capacity:
                storage: 8Gi
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: /mnt/redis-app-slave-1
