apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: app
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: frontend-5000
  selector:
    run: frontend
