apiVersion: v1
kind: PersistentVolume
metadata:
        name: redis-app-redis-ha-server-0
        labels:
                app: redis
                component: master
                heritage: Helm
                role: master
                release: redis-app
spec:
        #storageClassName: manual
        capacity:
                storage: 8Gi 
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: /mnt/redis-ha
