FROM python:3.7-alpine
COPY qemu-aarch64-static /usr/bin
WORKDIR /code
ENV FLASK_APP test.py
ENV FLASK_RUN_HOST 0.0.0.0
ENV FLASK_RUN_PORT 5050
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
CMD ["flask", "run"]
