{
 "title": "Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{nodename=~\"$hostname\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 18, "x": 6, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>Hardware Status</span>\n</div>"
  },
  {
   "title": "$node Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    }
   ]
  },
  {
   "title": "$node CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "$node Free RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$node used CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[30m])) * 100)"
    }
   ]
  },
  {
   "title": "192.168.205.11 Used RAM memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.205.11:9100\"} / (node_memory_MemTotal_bytes{instance=\"192.168.205.11:9100\"})))* 100"
    }
   ]
  },
  {
   "title": "192.168.205.11 CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"192.168.205.11:9100\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    }
   ]
  },
  {
   "title": "192.168.205.12 Used RAM memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.205.12:9100\"} / (node_memory_MemTotal_bytes{instance=\"192.168.205.12:9100\"})))* 100",
     "legendFormat": "Used RAM Memory"
    }
   ]
  },
  {
   "title": "192.168.205.12 CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"192.168.205.12:9100\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>Frontend Status</span>\n</div>"
  },
  {
   "title": "Client Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"frontend-svc.app.svc.cluster.local\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"frontend-svc.app.svc.cluster.local\"}[5m]))"
    }
   ]
  },
  {
   "title": "Client Success Rate (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"frontend-svc.app.svc.cluster.local\",response_code!~\"5.*\"}[5m])) / sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"frontend-svc.app.svc.cluster.local\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests per second (aprox)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(istio_requests_total{reporter=\"source\",destination_service=~\"frontend-svc.app.svc.cluster.local\"}[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>Redis Status</span>\n</div>"
  },
  {
   "title": "Redis-headless TCP Received Bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", destination_service=~\"redis-app-headless.app.svc.cluster.local\"}[1m]))"
    }
   ]
  },
  {
   "title": "Redis TCP Received Bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_received_bytes_total{reporter=\"source\", destination_service=~\"redis-app.app.svc.cluster.local\"}[1m]))"
    }
   ]
  },
  {
   "title": "Redis-headless TCP Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"source\", destination_service=~\"redis-app-headless.app.svc.cluster.local\"}[1m]))"
    }
   ]
  },
  {
   "title": "Redis TCP Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_tcp_sent_bytes_total{reporter=\"source\", destination_service=~\"redis-app.app.svc.cluster.local\"}[1m]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 22, "x": 1, "y": 33 },
   "content": "<div class=\"dashboard-header text-center\">\n<span></span>\n</div>"
  }
 ]
}